### ISSUE TITLE
Parsing errors not annotated

### ISSUE THREAD

**Issue by Zodiase** [ataylorme/eslint-annotate-action#13]
See error here: https://github.com/Zodiase/test-github-actions/pull/4/checks?check_run_id=1567114304#step:6:12

![image](https://user-images.githubusercontent.com/1815174/102418295-4dfbac80-3fb2-11eb-975c-88e8a2d8465c.png)

But the error is not annotated:
![image](https://user-images.githubusercontent.com/1815174/102418314-57851480-3fb2-11eb-860e-e15b99aee503.png)

**Comment by ataylorme** [comment]
@Zodiase thanks for reporting the issue. Can you attach the ESLint JSON report that is causing this error? I will use it to make a unit test and then write a fix.

**Comment by ataylorme** [comment]
@Zodiase after examining your failed action log and the workflow file in your branch I see the issue.

You have a step before saving the ESLint report and running my action [that calls `npm run lint`](https://github.com/Zodiase/test-github-actions/blob/run-eslint-directly-from-workflow/.github/workflows/eslint.yml#L42:L45). There is not `continue-on-error: true` so your workflow is failing with normal ESlint before it saves a report and runs my action.

You can see in the workflow log those steps are never run. Remove the `Run eslint` step from your workflow and it should work.
