### ISSUE TITLE
only-pr-files is not working

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [ataylorme/eslint-annotate-action#31]
I'm receiving the following warning:
`Warning: Unexpected input(s) 'only-pr-files', valid inputs are ['repo-token', 'report-json', 'fail-on-warning']`

**Comment by ataylorme** [comment]
Please check that you are using version ‘1.2.0’

**Comment by ricardovanlaarhoven** [comment]
Yes
`uses: ataylorme/eslint-annotate-action@1.2.0`

**Comment by ViktoriaKhaslarova** [comment]
For me either, got the warning 
"Warning: Unexpected input(s) 'only-pr-files', valid inputs are ['repo-token', 'report-json', 'fail-on-warning']"

**Comment by oxc** [comment]
I don't see it anywhere in the code, to be honest. Only in the README.

**Comment by ataylorme** [comment]
Sorry for the confusion here. Indeed this is in the README but not the code. I was planning to implement the feature until [GitHub added it natively in the UI](https://github.blog/changelog/2019-09-06-improved-check-annotations-on-the-files-changed-tab/). PRs with annotations outside the changed files appear separately

**Comment by oxc** [comment]
I see. What I had hoped for from that feature is that it ignores the many (legacy) errors we have in the project and only complains about the ones in the PR 😂 (I would not disagree if you said this was out of scope)

**Comment by ataylorme** [comment]
That was more or less the goal with an option to make non-pr changed errors report as warnings (if possible) or not at all.

I haven’t been able to give this project much attention as real life has been a priority for me.

If someone wanted to add the feature and make a PR I can help with code review and testing of it

**Comment by ataylorme** [comment]
I am making updates in a v2 refactor #44. Only PR files should now work. Can you test `ataylorme/eslint-annotate-action@v2`?

**Comment by ascrazy** [comment]
Just wanted to say that `only-pr-files` is very useful option. I've recently tests v2 branch on my repo and it works as expected. Great thanks!

**Comment by ataylorme** [comment]
@ascrazy thank you for testing! I’m glad v2 is working for you

**Comment by ataylorme** [comment]
`v2` is the default branch, closing this out as fixed
