### ISSUE TITLE
Max limits reached

### ISSUE THREAD

**Issue by IgnusG** [ataylorme/eslint-annotate-action#32]
Seems like if there are too many characters in the request (too many warnings) - the request to GitHub fails:

```
Error: Invalid request.

Only 65535 characters are allowed; 88012 were supplied.
```

> Version 1.2.0

**Comment by gpont** [comment]
@ataylorme , seems like if there are too many items in the lint report - it fails too:

```
Error: Invalid request.

No more than 50 items are allowed; 52 were supplied.
```

**Comment by ataylorme** [comment]
I am making updates in a v2 refactor #44. Can you test `ataylorme/eslint-annotate-action@v2`

**Comment by TemaSM** [comment]
@ataylorme Tested `ataylorme/eslint-annotate-action@v2` - works just great 👍

**Comment by ataylorme** [comment]
Thanks for testing @TemaSM. You can continue to reference v2. I’ll be making that the default branch/version and deprecating v1

**Comment by TemaSM** [comment]
Awesome! Thanks for maintaining this repo. Using this GH-action on daily basis 😃
