### ISSUE TITLE
Project doesn't have a license specified

### ISSUE THREAD

**Issue by johnbartholomew** [ataylorme/eslint-annotate-action#33]
Unless I missed seeing it somewhere, there's no license specified either as a file in the repo, or set in the [package.json license field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license).

It would be great if you could specify the license for this project, so that I know what my rights & obligations are if I want to make modifications (for contribution or otherwise).

**Comment by ataylorme** [comment]
MIT license added as part of v2 refactor in #44
