### ISSUE TITLE
Linting reports from a range of lines are being annotated on the end line instead of start line

### ISSUE THREAD

**Issue by lone-cloud** [ataylorme/eslint-annotate-action#45]
I'm testing v2 and am not sure if this behaviour is preset in v1.

An an example, I see a linting error being reported for "#L15-L71". This action puts the annotation with the error on line 71 which doesn't seem intuitive to me. I think it would be best to highlight the start of the problem which is on line 15.

**Comment by lone-cloud** [comment]
The code in this repo looks correct to me. Perhaps github is just displaying it weirdly. Here's a screenshot of what I mean. I was expecting to see this on line 15, not 71.
<img width="429" alt="2022-06-29 10_42_48-WEB-5846 add eslint annotations to PRs by egor-yolabs · Pull Request #2399 · yol" src="https://user-images.githubusercontent.com/595980/176502133-f559a87f-32c1-4f55-999c-2ec5cb892ad4.png">

**Comment by ataylorme** [comment]
I believe `start_line` and `end_line` are being passed correctly to the GitHub API. I am going to close this as a GitHub UI error. If you there there is something I can do to resolve this I'm happy to revisit.
