### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by Ridermansb** [ataylorme/eslint-annotate-action#49]
Gettings this error

```
0 ESLint error(s) and 0 ESLint warning(s) found in pull request changed files.
0 ESLint error(s) and 0 ESLint warning(s) found in files outside of the pull request.

✖  fatal     Resource not accessible by integration
```

running `eslint --ext .ts,.tsx --output-file eslint_report.json --format json .`

with this GH action

```
      - name: Save Code Linting Report JSON
        run: yarn lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

```

**Comment by atsu85** [comment]
This error also happens for PRs created by dependabot. Based on [issue](https://github.com/ataylorme/eslint-annotate-action/issues/42#issue-1191887459) created by GitHub bot this, it seems that `checks: write` is required.

I couldn't find anything related to granting custom permissions for dependabot for the repo:
* [dependabot.yaml documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
    * custom [token](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries) (for example PAT with custom permissions) could only be passed to registries, but in this case access is needed for PR target repo instead
* googling
* from GitHub GUI (neither from repo nor organization level)

Please let me know if you find a solution for dependabot, but currently i used following workaround to disable it for dependabot PRs:
```diff
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
+        if: ${{ github.actor != 'dependabot[bot]' }} # dependabot doesn't have permissions
```

**Comment by ataylorme** [comment]
@atsu85 @Ridermansb this is a permission error with `GITHUB_TOKEN` when running from pull request from forks.

[`GITHUB_TOKEN` for pull requests from forks is limited to read access](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) and the Action requires `write` to status checks to do the annotations

For security reasons I would not encourage trying to bypass this. You might be able to use the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to determine if a PR is from a fork and skip the annotation step with `if` as @atsu85 has shown an example of

You could still have the ESLint step prior run and fail if there are linting errors, there just won't be annotation
