### ISSUE TITLE
Feature Request: warn when annotations can't be added because of filePath mismatch

### ISSUE THREAD

**Issue by atsu85** [ataylorme/eslint-annotate-action#50]
# Suggestion
Log warning when `filePath`s from referenced `report-json` file contain paths that don't match with files in repository.

# Background information
I wasted some time until i figured out why this action didn't add linting annotations next to "Files changed" tab of the PR nor to individual commits.

The reason was that since i run linter inside Docker container, not in runner directly, and `filePath`s of generated report json are absolute paths, not relative, then linting issues could not be correctly correlated to files in the git repository. Hence the annotations didn't appear next to code changes, although they could be viewed from the separate report.

As workaround i started running linter in runner directly, not in Docker container, but for larger projects this approach could be considerably slower. In one of my projects it takes:
* 3:25 to prepare linting in runner (checkout, node setup, downloading dependencies) 
* 49 sec to download docker image containing code to be linted

Another workaround could have been to replace absolute paths of docker container with absolute paths of runner in `report-json` file - seemed too much hassle.

**Comment by ataylorme** [comment]
>Another workaround could have been to replace absolute paths of docker container with absolute paths of runner in report-json file - seemed too much hassle.

This action takes a report as an input and I see the path issues as a problem with the report file, not the action.
