### ISSUE TITLE
Is it possible to also post the linting errors as a PR comment?

### ISSUE THREAD

**Issue by zomars** [ataylorme/eslint-annotate-action#63]
Trying to achieve this:

![](https://user-images.githubusercontent.com/22801583/134893502-d7f02f30-85ac-4402-a58c-bb64c62d92e1.png)

Thank you for such an awesome tool BTW 🙏🏽

**Comment by ataylorme** [comment]
@zomars try out the new report markdown feature from @velocibear added in #65. This has been released in `2.2.0`
