### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by szepeviktor** [ataylorme/eslint-annotate-action#67]
The last tagged commit is for v1
https://github.com/ataylorme/eslint-annotate-action/tags

I use concrete tags
```yaml
uses: "ataylorme/eslint-annotate-action@1.2.0"
```

Would it be any help if I list `git tag` commands here?

**Comment by ataylorme** [comment]
I published a tag for `2.1.1` and will publish `2.2.0` when it is ready for release

https://github.com/ataylorme/eslint-annotate-action/releases/tag/2.1.1

**Comment by szepeviktor** [comment]
Thank you.
