### ISSUE TITLE
end_column cannot be null

### ISSUE THREAD

**Issue by swissspidy** [ataylorme/eslint-annotate-action#7]
We're sometimes getting the following error:

```
##[error]'output.annotations[1].end_column' cannot be null
```

It looks like `endColumn` as reported by ESLint can indeed sometimes be `null`.

Would be great if there'd be a check for that before adding the annotation:

https://github.com/ataylorme/eslint-annotate-action/blob/95223b5a6464769fc74e9e8229f095ae7c678761/src/analyze-eslint-js.ts#L75-L78

**Comment by ataylorme** [comment]
@swissspidy thanks for teh bug report. I haven't run into this issue but I can certainly account for it.

What version of ESLint are you running? If you can attach a copy of a report that has this issue that would be helpful.

**Comment by swissspidy** [comment]
I'm currently using ESLint 7.2, although the error has been happening even before ESLint 7.x was out.

Here's a report that has the issue:

[lint-js-report.json.zip](https://github.com/ataylorme/eslint-annotate-action/files/4787729/lint-js-report.json.zip)

It's from the https://github.com/google/web-stories-wp repo.

The issue seems to stem from `jsdoc/check-tag-names` warning about unexpected `@todo` tag in a function doc block, in case that helps.

**Comment by ataylorme** [comment]
@swissspidy for transparency I am going to test out https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/, which was just released. It seems to also provide a lint report/check, though it looks like it might not do annotations.

If it works for my needs I may adopt the GitHub maintained solution and archive this project. If you have thoughts on the GitHub Super linter or why this Action would still be a better fit I'd love to hear them.

**Comment by swissspidy** [comment]
Sounds good to me. I'm gonna test the super linter myself to see if it fits our needs and provide feedback here.

**Comment by ataylorme** [comment]
@swissspidy FYI here were my findings on the GitHub Super Linter:

Overall it looks like the GitHub Super Linter is missing two features that I like about this action.

1. Being able to extend custom ESLint rulesets/shared configuration. The Super Linter is in it's own environment and can only extend the few packages installed there (e.g. `eslint:recommended`).
1. Annotating PRs with code linting results, so the results are easily visible to the pull request author and not buried in the failed action workflow logs

Annotating PRs I could probably live without but our team has a custom, shared ESLint config that we extend. While we could use that with the Super Linter it would be the only config. The capability for projects to override rules when extending the shared config would be gone.

As an example, our shared config has a line length limit of `120` and some projects override that to `200`, skip enforcing a few specific rules, etc.

**Comment by ataylorme** [comment]
@swissspidy [version `1.1.2`](https://github.com/ataylorme/eslint-annotate-action/releases/tag/1.1.2) has been published with the fix in #8. Thanks for reporting the issue

**Comment by swissspidy** [comment]
@ataylorme I'm now getting `'output.annotations[0].start_column' cannot be null` in some areas...

https://github.com/google/web-stories-wp/pull/5572/checks?check_run_id=1500127987#step:8:9
