### ISSUE TITLE
`Only 65535 characters are allowed` error

### ISSUE THREAD

**Issue by dancrumb** [ataylorme/eslint-annotate-action#70]
This looks like a regression of #32 

My config is:

```
- name: Generate Lint Report
      if: "!cancelled()"
      uses: ataylorme/eslint-annotate-action@2.2.0
      with:
        report-json: ${{ inputs.workspace-name }}-eslint_report.json
        repo-token: "${{ inputs.github_token }}"
        check-name: "${{inputs.workspace-description}} Lint Report"
        fail-on-error: false
        markdown-report-on-step-summary: true
```

The logs look fine until:
```
...
ℹ  info      Analyzing <filename>
ℹ  info      Analyzing <filename>
ℹ  info      Analyzing <filename>
ℹ  info      
0 ESLint error(s) and 0 ESLint warning(s) found in pull request changed files.
0 ESLint error(s) and 164 ESLint warning(s) found in files outside of the pull request.

✖  fatal     Invalid request.

Only 65535 characters are allowed; 68338 were supplied.
```

**Comment by oxc** [comment]
We're hitting the same issue. I assume this only happens with `markdown-report-on-step-summary: true` (we have a lot of warnings 😞)

**Comment by ValentinGurkov** [comment]
I'm experiencing the same unfortunately, does anybody know of a workaround that does not involve suppressing the warnings? Because on a large monorepo with microservices, we've got something like:
`Only 65535 characters are allowed; 320944 were supplied.` which is waaaay above the limit

**Comment by ataylorme** [comment]
This seems like a character limit on the check run summary.

> does anybody know of a workaround that does not involve suppressing the warnings

I don't know if there is a good answer without simplifying the summary to include the number of errors and warnings without actually listing them all out.

**Comment by ValentinGurkov** [comment]
> This seems like a character limit on the check run summary.
> 
> > does anybody know of a workaround that does not involve suppressing the warnings
> 
> I don't know if there is a good answer without simplifying the summary to include the number of errors and warnings without actually listing them all out.

I'd support the idea of  a such minimal summary and we can look into other ways of obtaining a complete list

**Comment by ataylorme** [comment]
I am working on `v3` (in progress) and will make it so when `only-pr-files` is `true` only those files are included in the summary. Please let me know if any of you are interested in helping to test that version.

edit: to test please update your action reference to `uses: ataylorme/eslint-annotate-action@v3-beta`

**Comment by ataylorme** [comment]
I also [truncated the summary if it is too long](https://github.com/ataylorme/eslint-annotate-action/commit/748e7053bf8ac2c5e4fe0240c20d3242e54d3ab6)

**Comment by ataylorme** [comment]
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`. Make sure to read the Changelog as there are breaking changes (GH_TOKEN input has changed)
