### ISSUE TITLE
Bug: For 'properties/start_column', nil is not an integer.

### ISSUE THREAD

**Issue by andys8** [ataylorme/eslint-annotate-action#72]
## Issue

We see an issue where there is an error `nil is not integer` resulting in a hanging result / check job.

```shell
2 ESLint error(s) and 0 ESLint warning(s) found in pull request changed files.
0 ESLint error(s) and 0 ESLint warning(s) found in files outside of the pull request.

ℹ  info      Found 2 ESLint errors and warnings, processing batch 1 of 1...
✖  fatal     Invalid request.

For 'properties/start_column', nil is not an integer.
For 'properties/start_column', nil is not an integer.
```

Leads to dangling / hanging result lint CI job:

![image](https://github.com/ataylorme/eslint-annotate-action/assets/13085980/02ab7b18-42bd-4332-8915-e2e4ece2c7ba)

## Github Action

```yml
      - name: Lint
        run: yarn lint --output-file eslint_report.json --format json
        working-directory: ./apps/dashboard/
        continue-on-error: true

      - name: Annotate Linting Results
        uses: ataylorme/eslint-annotate-action@2.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./apps/dashboard/eslint_report.json"
          fail-on-warning: ${{ github.event_name == 'pull_request' }}
          only-pr-files: true
          check-name: "Lint Result Dashboard"
```

Is this an issue with the action? Can we provide more information to solve this issue?

Maybe related, but by the name: https://github.com/ataylorme/eslint-annotate-action/pull/17

**Comment by ataylorme** [comment]
@andys8 can you please provide a copy of the ESLint report `.json` file that causes this error? I would like to use it to build a unit test

**Comment by andys8** [comment]
I don't think I've data or can reproduce it at this point (2 months later, setup changed), but I will keep an eye open if we encounter the issue again.

**Comment by ataylorme** [comment]
No worries, sorry for the delayed reply on my end.

**Comment by andys8** [comment]
Encountered the issue. The output is from a client, redacted, looks roughly like this.

Main issue is likely `column` being `null`. Not sure if that's allowed / within spec, but that's likely the input and reason for the action to fail.

```
 {
   "filePath": "/path/to/file.json",
   "messages": [
     {
       "ruleId": "i18n-json/identical-keys",
       "severity": 2,
       "message": "my message",
       "line": 0,
       "column": null,
       "nodeType": null
     }
   ],
   "errorCount": 1,
   "warningCount": 0,
   "fixableErrorCount": 0,
   "fixableWarningCount": 0,
   "source": "{}",
   "usedDeprecatedRules": []
 }
```

**Comment by ataylorme** [comment]
Thanks for the example. It should be fixed in [this commit](https://github.com/ataylorme/eslint-annotate-action/commit/f7515a7e6051aac225f505ed9b86421bed8f786d) in the `v3-beta`. I'll let you know when there is a `3.0.0` release for testing

**Comment by ataylorme** [comment]
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`
