### ISSUE TITLE
Node 16 is deprecated, blocking my Github actions on warning.

### ISSUE THREAD

**Issue by StraubRG** [ataylorme/eslint-annotate-action#73]
Please update project to Node 20.

**Comment by ataylorme** [comment]
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0) with Node 20 support. Please update any references to the `v3` branch instead of `v3-beta`. Make sure to read the Changeling as there are breaking changes (GH_TOKEN input has changed)
