### ISSUE TITLE
Feature request: only add entries to the summary report for files in the PR

### ISSUE THREAD

**Issue by tom-sherman** [ataylorme/eslint-annotate-action#74]
We have many warnings, but they're rarely useful on PRs because they're in a completely different part of the codebase. I'd like to only include files in the PR in the step summary.

This could help with #70

**Comment by ataylorme** [comment]
I am working on `v3` (in progress) and will make it so when `only-pr-files` is `true` only those files are included in the summary. Please let me know if you are interested in helping to test that version.

edit: to test please update your action reference to `uses: ataylorme/eslint-annotate-action@v3-beta`

**Comment by ataylorme** [comment]
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`
