### ISSUE TITLE
v3 release timeline

### ISSUE THREAD

**Issue by INRIX-Iurii-Okhmat** [ataylorme/eslint-annotate-action#79]
@ataylorme 
First of, thank you for this action.
I've been using `v3-beta` for a few weeks now across 20+ projects with no issues so far 
And, with the NodeJS v20 upgrade deadline looming, I'd like to ask if there's a specific timeline for `v3` GA?

**Comment by ataylorme** [comment]
Thanks for the feedback @INRIX-Iurii-Okhmat. I have only had 1 person comment on testing v3, I have been waiting for more feedback. Your success across multiple projects is reassuring!

I'll look to do a v3 release by the end of April at the latest.

**Comment by ataylorme** [comment]
[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`
